# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

#***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.                  
# SIMPLY APPEND THE REQUIRD VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
#***********************************************************************

# Kubernetes pod network CIDR for appliance k8s network
# Make sure this value does not overlap with any of the host networks.
# Default value: "192.168.0.0/16"
appliance_k8s_pod_net_cidr: "192.168.0.0/16"

# This variable is used to enable iDRAC telemetry support and visualizations
# Accepted values:  "true" or "false"
idrac_telemetry_support: false

# This variable is used to enable omnia telemetry support
# Accepted values:  "true" or "false"
omnia_telemetry_support: false

# Username used for connecting to timescale db
# The username must not contain -,\, ',"
# The Length of the username should be at least 2 characters.
# Mandatory field
timescaledb_user: "omnia"

# Password used for connecting to timescale db
# The password must not contain -,\, ',",@
# The Length of the password should be at least 2 characters.
# Mandatory field
timescaledb_password: ""

##### BELOW VARIABLES ARE MANDATORY WHEN idrac_telemetry_support IS SET TO true
# The username for idrac
# The username must not contain -,\, ',"
# Required only if idrac_telemetry_support is true
idrac_username: ""

# Password used for idrac
# The password must not contain -,\, ',"
# Required only if idrac_telemetry_support is true
idrac_password: ""

##### BELOW VARIABLES ARE MANDATORY WHEN omnia_telemetry_support IS SET TO true
# Below values give user an option to select what all metrics need to be discovered
# Default value for all the metrics is true
# Accepted values: "true" or "false"
# Required only if omnia_telemetry_support is true
collect_regular_metrics: true
collect_health_check_metrics: true
collect_gpu_metrics: true

# This value will have minimum 60 seconds and maximum 3600 seconds i.e., 1 minute to 1 hour.
# The values mentioned is in seconds.
# Default value is 300 seconds
# Required only if omnia_telemetry_support is true
omnia_telemetry_collection_interval: 300

# This is an advanced setting parameter for omnia_telemetry
# This offset will be added to telemetry collection interval to avoid all nodes collecting at the same time.
# For larger cluster this offset can be set to higher value.
# Default value: 60
# Required only if omnia_telemetry_support is true
fuzzy_offset: 60

# This is an advanced setting parameter for omnia_telemetry
# This value should be less than omnia_telemetry_collection_interval
# The value mentioned is in seconds.
# Default value is 5 seconds
# Required only if omnia_telemetry_support is true
metric_collection_timeout: 5
