# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

#***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.                  
# SIMPLY APPEND THE REQUIRD VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
#***********************************************************************

# Kubernetes pod network CIDR for appliance k8s network
# Make sure this value does not overlap with any of the host networks.
# Default value: "192.168.0.0/16"
appliance_k8s_pod_net_cidr: "192.168.0.0/16"

# This variable is used to enable iDRAC telemetry support and visualizations
# Accepted values:  "true" or "false"
idrac_telemetry_support: false

# Username used for connecting to timescale db
# The username must not contain -,\, ',"
# The Length of the username should be at least 2 characters.
# Mandatory field
timescaledb_user: "omnia"

# Password used for connecting to timescale db
# The password must not contain -,\, ',",@
# The Length of the password should be at least 2 characters.
# Mandatory field
timescaledb_password: ""

##### BELOW VARIABLES ARE MANDATORY WHEN idrac_telemetry_support IS SET TO true
# The username for idrac
# The username must not contain -,\, ',"
# Required only if idrac_telemetry_support is true
idrac_username: ""

# Password used for idrac
# The password must not contain -,\, ',"
# Required only if idrac_telemetry_support is true
idrac_password: ""

### ADVANCE CONFIGURATIONS FOR IDRAC TELEMETRY ###
# Username used for connecting to mysql db
# The username must not contain -,\, ',"
# The Length of the username should be at least 2 characters.
# Mandatory field when idrac_telemetry_support is true
mysqldb_user: ""

# Password used for connecting to mysql db
# The password must not contain -,\, ',"
# The Length of the password should be at least 2 characters.
# Mandatory field when idrac_telemetry_support is true
mysqldb_password: ""

# Password used for connecting to timescale db for root user
# The password must not contain -,\, ',"
# The Length of the password should be at least 2 characters.
# Mandatory field when idrac_telemetry_support is true
mysqldb_root_password: ""

# This variable is used to start or stop omnia telemetry
# Accepted values:  "true" or "false"
# If omnia_telemetry_support is true, then at least one of collect_regular_metrics or collect_health_check_metrics or collect_gpu_metrics should be true, to collect metrics
# If omnia_telemetry_support is false, telemetry acquisition will be stopped
omnia_telemetry_support: true

# This variable denotes the time interval of telemerey data collection from required computue nodes
# Default value is 300 seconds
# Valid range: minimum 60 seconds and maximum 3600 seconds(i.e. 1 minute to 1 hour)
omnia_telemetry_collection_interval: 300

# This variable is used to enable metric collection part of the regular metric group
# Accepted values:  "true" or "false"
collect_regular_metrics: true

# This variable is used to enable metric collection related to health check
# Accepted values:  "true" or "false"
collect_health_check_metrics: true

# This variable is used to enable metric collection related to GPU
# Accepted values:  "true" or "false"
collect_gpu_metrics: true

# Advanced Setting for omnia Telemetry

# This variable is used to set an appropriate time interval for all compute nodes so that they do not congest the admin network
# A random rumber between 0 and fuzzy_offset gets added with omnia_telemetry_collection_interval value to decide individual compute node's telemetry data collection interval
# Default value is 60 seconds
# For larger cluster this parameter can be set with higher value
# This value should be less than omnia_telemetry_collection_interval value
fuzzy_offset: 60

# This variable is used to define data collection timeout period
# Default value is 5 sec
# This value should be less than omnia_telemetry_collection_interval value
metric_collection_timeout: 5
