# Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Include telemetry_config_file.yml

- name: Check that the telemetry_config.yml exists
  ansible.builtin.stat:
    path: "{{ telemetry_config_file }}"
  register: stat_result

- name: Fail if telemetry_config.yml file doesn't exist
  ansible.builtin.fail:
    msg: "{{ fail_msg_telemetry_config_file }}"
  when: not stat_result.stat.exists

- name: Check telemetry_config.yml file is encrypted
  ansible.builtin.command: cat {{ telemetry_config_file }}
  changed_when: false
  register: config_content
  no_log: true

- name: Decrpyt telemetry_login_vars.yml
  ansible.builtin.command: >-
    ansible-vault decrypt {{ telemetry_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
  when: "'$ANSIBLE_VAULT;' in config_content.stdout"

- name: Include variable file telemetry_config.yml
  ansible.builtin.include_vars: "{{ telemetry_config_file }}"
  no_log: true

- name: Assert idrac telemetry support
  ansible.builtin.assert:
    that:
      - idrac_telemetry_support == true or idrac_telemetry_support == false
    quiet: true
    success_msg: "{{ idrac_telemetry_support_success_msg }}"
    fail_msg: "{{ idrac_telemetry_support_fail_msg }}"

- name: Assert omnia telemetry support
  ansible.builtin.assert:
    that:
      - omnia_telemetry_support == true or omnia_telemetry_support == false
    quiet: true
    success_msg: "{{ omnia_telemetry_support_success_msg }}"
    fail_msg: "{{ omnia_telemetry_support_fail_msg }}"

- name: Check k8s is installed or not
  ansible.builtin.command: kubectl get pods -A
  changed_when: false
  failed_when: false
  register: k8s_pods

- name: Validate k8s_pod_net_cidr
  when: "'nfs-client-provisioner' not in k8s_pods.stdout"
  block:
    - name: Assert kubernetes pod network CIDR
      ansible.builtin.assert:
        that:
          - appliance_k8s_pod_net_cidr | ansible.utils.ipv4
          - appliance_k8s_pod_net_cidr | length > 9
          - '"/" in appliance_k8s_pod_net_cidr '
        success_msg: "{{ success_msg_k8s_pod_network_cidr }}"
        fail_msg: "{{ fail_msg_k8s_pod_network_cidr }}"
      when: idrac_telemetry_support is true

    - name: Set kubernetes pod CIDR
      ansible.builtin.set_fact:
        k8s_net_cidr: "{{ appliance_k8s_pod_net_cidr }}"

- name: Assert usernames and passwords in telemetry_login_vars.yml
  block:
    - name: Assert timescaledb user name
      ansible.builtin.assert:
        that:
          - timescaledb_user | length > 1
          - '"-" not in timescaledb_user '
          - '"\\" not in timescaledb_user '
          - '"\"" not in timescaledb_user '
          - " \"'\" not in timescaledb_user "
      no_log: true

    - name: Assert timescaledb user password
      ansible.builtin.assert:
        that:
          - timescaledb_password | length > 1
          - '"-" not in timescaledb_password '
          - '"\\" not in timescaledb_password '
          - '"\"" not in timescaledb_password '
          - " \"'\" not in timescaledb_password "
          - '"@" not in timescaledb_password '
      no_log: true

  rescue:
    - name: Validation issue in telemetry_config.yml
      ansible.builtin.fail:
        msg: "{{ login_vars_fail_msg }}"

- name: Verify iDRAC username and password
  when: idrac_telemetry_support
  block:
    - name: Assert idrac_username and idrac_password
      ansible.builtin.assert:
        that:
          - idrac_username | length >= min_length_idrac
          - idrac_username | length < max_length
          - '"-" not in idrac_username '
          - '"\\" not in idrac_username '
          - '"\"" not in idrac_username '
          - " \"'\" not in idrac_username "
          - idrac_password | length > min_length_idrac | int - 1
          - idrac_password | length < max_length | int + 1
          - '"-" not in idrac_password '
          - '"\\" not in idrac_password '
          - '"\"" not in idrac_password '
          - " \"'\" not in idrac_password "
      no_log: true
  rescue:
    - name: Extra variables not provided correctly
      ansible.builtin.fail:
        msg: "{{ idrac_credentials_fail_msg }}"

# Add validation for omnia_telemetry_support and idrac_telemetry_support can not be false together

- name: Verify omnia_telemetry parameters
  when: omnia_telemetry_support
  block:
    - name: Assert the collect metrics values
      ansible.builtin.assert:
        that:
          - collect_regular_metrics == true or collect_regular_metrics == false
          - collect_health_check_metrics == true or collect_health_check_metrics == false
          - collect_gpu_metrics == true or collect_gpu_metrics == false
        quiet: true
        success_msg: "{{ collect_metrics_success_msg }}"
        fail_msg: "{{ collect_metrics_fail_msg }}"

    - name: Assert the omnia_telemetry_collection_interval
      ansible.builtin.assert:
        that:
          - omnia_telemetry_collection_interval >= 60
          - omnia_telemetry_collection_interval <= 3600
        quiet: true
        success_msg: "{{ collection_interval_success_msg }}"
        fail_msg: "{{ collection_interval_fail_msg }}"

    - name: Assert the fuzzy_offset value
      ansible.builtin.assert:
        that:
          - fuzzy_offset != ""
          - fuzzy_offset is not none
          - fuzzy_offset is defined
        quiet: true
        success_msg: "{{ fuzzy_offset_success_msg }}"
        fail_msg: "{{ fuzzy_offset_fail_msg }}"

    - name: Assert the metric_collection_timeout value
      ansible.builtin.assert:
        that:
          - metric_collection_timeout != ""
          - metric_collection_timeout is not none
          - metric_collection_timeout is defined
          - metric_collection_timeout < omnia_telemetry_collection_interval
        quiet: true
        success_msg: "{{ metric_collection_timeout_success_msg }}"
        fail_msg: "{{ metric_collection_timeout_fail_msg }}"

- name: Create ansible vault key
  ansible.builtin.set_fact:
    vault_key: "{{ lookup('password', '/dev/null chars=ascii_letters') }}"
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Save vault key
  ansible.builtin.lineinfile:
    path: "{{ vault_filename }}"
    line: "{{ vault_key }}"
    mode: "{{ vault_file_perm }}"
    owner: root
    create: true
  when: "'$ANSIBLE_VAULT;' not in config_content.stdout"

- name: Encrypt telemetry_config.yml file
  ansible.builtin.command: >-
    ansible-vault encrypt {{ telemetry_config_file }}
    --vault-password-file {{ vault_filename }}
  changed_when: false
